// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1bpRSNCIh4la4GVmr6q6do8EpFggcnuI',
    appId: '1:283668579490:web:be48477f3e243a016e83fb',
    messagingSenderId: '283668579490',
    projectId: 'bookread-efbc2',
    authDomain: 'bookread-efbc2.firebaseapp.com',
    storageBucket: 'bookread-efbc2.firebasestorage.app',
    measurementId: 'G-STJQQPVZEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgIKDQ-EmomVDEc8SRg5FzQiXOeXyKTAY',
    appId: '1:283668579490:android:aa8eb5d8ee909ac46e83fb',
    messagingSenderId: '283668579490',
    projectId: 'bookread-efbc2',
    storageBucket: 'bookread-efbc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaOqnzcBw4Fb6p2HnHPUz15dgaoqevcTY',
    appId: '1:283668579490:ios:0cf9522e9580100e6e83fb',
    messagingSenderId: '283668579490',
    projectId: 'bookread-efbc2',
    storageBucket: 'bookread-efbc2.firebasestorage.app',
    iosBundleId: 'com.yourname.banglaRead',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaOqnzcBw4Fb6p2HnHPUz15dgaoqevcTY',
    appId: '1:283668579490:ios:0cf9522e9580100e6e83fb',
    messagingSenderId: '283668579490',
    projectId: 'bookread-efbc2',
    storageBucket: 'bookread-efbc2.firebasestorage.app',
    iosBundleId: 'com.yourname.banglaRead',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1bpRSNCIh4la4GVmr6q6do8EpFggcnuI',
    appId: '1:283668579490:web:614c02477ea7f5f36e83fb',
    messagingSenderId: '283668579490',
    projectId: 'bookread-efbc2',
    authDomain: 'bookread-efbc2.firebaseapp.com',
    storageBucket: 'bookread-efbc2.firebasestorage.app',
    measurementId: 'G-HXRQ0G9DY5',
  );
}
